# Alacritty configuration

[window]
opacity = 0.6

[font]
normal = { family = "JetBrains Mono", style = "Regular" }
bold = { family = "JetBrains Mono", style = "Bold" }
italic = { family = "JetBrains Mono", style = "Italic" }
bold_italic = { family = "JetBrains Mono", style = "Bold Italic" }
size = 12

[scrolling]
multiplier  = 10

[colors]
# Default colors
[colors.primary]
background = '0x000000' # Black
foreground = '0x88B97D' # White

# Normal colors (The standard 8 colors, often referred to as 'ANSI' colors)
[colors.normal]
black   = '0x000000'
red     = '0xCD0000'
green   = '0x00CD00'
yellow  = '0xCDCD00'
blue    = '0x0000EE'
magenta = '0xCD00CD'
cyan    = '0x00CDCD'
white   = '0xE5E5E5'

# Bright colors (The bright 8 colors)
[colors.bright]
black   = '0x7F7F7F'
red     = '0xFF0000'
green   = '0x00FF00'
yellow  = '0xFFFF00'
blue    = '0x5C5CFF' # A common bright blue in XTerm
magenta = '0xFF00FF'
cyan    = '0x00FFFF'
white   = '0xFFFFFF'

[env]
TERM = "xterm-256color"
